/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { Sum } from './components/railz-nested/types/sum';
export namespace Components {
  interface RailzComponent {
    /**
     * The first name
     * @type string
     * @default ''
     */
    first: string;
    /**
     * The last name
     * @type string
     * @default ''
     */
    last: string;
    /**
     * The middle name
     * @type string
     * @default ''
     */
    middle: string;
  }
  interface RailzNested {
    /**
     * The list of numbers to sum up
     * @type Sum
     * @default []
     */
    sumList: Sum[];
  }
  interface RailzNestedSum {
    /**
     * The first number to sum up
     * @type number
     * @default 0
     */
    first: number;
    /**
     * The second number
     * @type number
     * @default 0
     */
    second: number;
  }
}
declare global {
  interface HTMLRailzComponentElement extends Components.RailzComponent, HTMLStencilElement {}
  var HTMLRailzComponentElement: {
    prototype: HTMLRailzComponentElement;
    new (): HTMLRailzComponentElement;
  };
  interface HTMLRailzNestedElement extends Components.RailzNested, HTMLStencilElement {}
  var HTMLRailzNestedElement: {
    prototype: HTMLRailzNestedElement;
    new (): HTMLRailzNestedElement;
  };
  interface HTMLRailzNestedSumElement extends Components.RailzNestedSum, HTMLStencilElement {}
  var HTMLRailzNestedSumElement: {
    prototype: HTMLRailzNestedSumElement;
    new (): HTMLRailzNestedSumElement;
  };
  interface HTMLElementTagNameMap {
    'railz-component': HTMLRailzComponentElement;
    'railz-nested': HTMLRailzNestedElement;
    'railz-nested-sum': HTMLRailzNestedSumElement;
  }
}
declare namespace LocalJSX {
  interface RailzComponent {
    /**
     * The first name
     * @type string
     * @default ''
     */
    first?: string;
    /**
     * The last name
     * @type string
     * @default ''
     */
    last?: string;
    /**
     * The middle name
     * @type string
     * @default ''
     */
    middle?: string;
  }
  interface RailzNested {
    /**
     * The list of numbers to sum up
     * @type Sum
     * @default []
     */
    sumList?: Sum[];
  }
  interface RailzNestedSum {
    /**
     * The first number to sum up
     * @type number
     * @default 0
     */
    first?: number;
    /**
     * The second number
     * @type number
     * @default 0
     */
    second?: number;
  }
  interface IntrinsicElements {
    'railz-component': RailzComponent;
    'railz-nested': RailzNested;
    'railz-nested-sum': RailzNestedSum;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'railz-component': LocalJSX.RailzComponent & JSXBase.HTMLAttributes<HTMLRailzComponentElement>;
      'railz-nested': LocalJSX.RailzNested & JSXBase.HTMLAttributes<HTMLRailzNestedElement>;
      'railz-nested-sum': LocalJSX.RailzNestedSum & JSXBase.HTMLAttributes<HTMLRailzNestedSumElement>;
    }
  }
}
