name: Publish Docs

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:
    inputs:
      yarnCommand:
        type: string
        description: 'Trigger version generation, input your version'
        required: true
        default: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/docs
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Copy repo code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install testing dependencies
        run: yarn install

      - name: Run Build
        run: yarn build

      - name: Run Copy Version
        if: github.event.inputs.yarnCommand != ''
        run: VERSION="${{ github.event.inputs.yarnCommand }}" yarn cp:version

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/railz-ai/railz-uikit.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
